- name: Create roles and users for PostgreSQL
  hosts: localhost
  become: true
  vars:
    db_roles:
      - name: read_only
        login: false
      - name: read_write
        login: false
    db_users:
      - name: monitoring_user
        password: "NE&h2Gjqw6"
        memberof: read_only
      - name: app_user
        password: "C+2Atg4%uT"
        memberof: read_write
  tasks:
    - name: Create roles without login privilege
      community.postgresql.postgresql_user:
        name: "{{ item.name }}"
        role_attr_flags: "NOLOGIN"
        state: present
      loop: "{{ db_roles }}"
      
    - name: Create users with login privilege
      community.postgresql.postgresql_user:
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        role_attr_flags: "LOGIN"
        state: present
      loop: "{{ db_users }}"
      
    - name: Grant role membership to users
      community.postgresql.postgresql_membership:
        user: "{{ item.name }}"
        groups: ["{{ item.memberof }}"]
        state: present
      loop: "{{ db_users }}"
      when: item.memberof is defined








