# This playbook creates a test database for PostgreSQL
- name: Create PostgreSQL database
  hosts: localhost
  become: true
  tasks:
    - name: Create a new PostgreSQL database
      community.postgresql.postgresql_db:
        name: testdb
        owner: postgres
