- name: Create tables in database testdb
  hosts: localhost
  become: true
  vars:
    db_name: testdb
    
  tasks:
    - name: Create table student
      community.postgresql.postgresql_query:
        db: "{{ db_name }}"
        query: |
          CREATE TABLE IF NOT EXISTS public.student (
            id SERIAL PRIMARY KEY,
            first_name VARCHAR(45) NOT NULL,
            last_name VARCHAR(45) NOT NULL,
            email TEXT UNIQUE NOT NULL
          );
          
    - name: Create table course
      community.postgresql.postgresql_query:
        db: "{{ db_name }}"
        query: |
          CREATE TABLE IF NOT EXISTS public.course (
            id SERIAL PRIMARY KEY,
            title VARCHAR(80) NOT NULL,
            start_date DATE,
            duration INTEGER
          );
          
    - name: Create table enrollment
      community.postgresql.postgresql_query:
        db: "{{ db_name }}"
        query: |
          CREATE TABLE IF NOT EXISTS public.enrollment (
            date TIMESTAMP DEFAULT NOW(),
            student_id INTEGER NOT NULL REFERENCES public.student(id),
            course_id INTEGER NOT NULL REFERENCES public.course(id),
            PRIMARY KEY (student_id, course_id, date)
          );
