- name: Grant privileges on test database
  hosts: localhost
  become: true
  vars:
    db_name: test_db
    db_privileges:
      - user: read_only
        privileges: SELECT
      - user: read_write
        privileges: ALL
  tasks:
    - name: Grant privileges to users
      community.postgresql.postgresql_privs:
        database: "{{ db_name }}"
        type: table
        privs: "{{ item.privileges }}"
        objs: ALL_IN_SCHEMA
        schema: public
        roles: "{{ item.user }}"
        state: present
      loop: "{{ db_privileges }}"
